// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.LiteDb;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240306220306_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Repository.LiteDb.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = 3,
                            Height = 0,
                            Name = "User1"
                        },
                        new
                        {
                            Id = 2L,
                            Age = 7,
                            Height = 0,
                            Name = "User2"
                        },
                        new
                        {
                            Id = 3L,
                            Age = 15,
                            Height = 0,
                            Name = "User3"
                        },
                        new
                        {
                            Id = 4L,
                            Age = 18,
                            Height = 0,
                            Name = "User4"
                        },
                        new
                        {
                            Id = 5L,
                            Age = 22,
                            Height = 0,
                            Name = "User5"
                        },
                        new
                        {
                            Id = 6L,
                            Age = 35,
                            Height = 0,
                            Name = "User6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
